title: Lemon Doroshow
email: isaacdoroshow@gmail.com
description: "Applied math and Earth sciences student, interested in ecological and oceanographic modeling"
baseurl: "/"
url: "https://lemondoroshow.github.io/"

# Build settings
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# Console theme settings
header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md
style: dark
footer: ''

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console